name: Deploy to Server
on:
  push:
    branches:
      - main # Укажите ветку для развертывания

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 194.87.232.2 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -v root@194.87.232.2 "cd /testwebdeploy && git pull && npm install && npm run build"
